/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdfViewRouteImport } from './routes/pdf-view'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPdfPickerRouteImport } from './routes/dashboard/pdf-picker'
import { Route as DashboardConnectionStatusRouteImport } from './routes/dashboard/connection-status'
import { Route as DashboardConnectionSettingsRouteImport } from './routes/dashboard/connection-settings'

const PdfViewRoute = PdfViewRouteImport.update({
  id: '/pdf-view',
  path: '/pdf-view',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPdfPickerRoute = DashboardPdfPickerRouteImport.update({
  id: '/pdf-picker',
  path: '/pdf-picker',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConnectionStatusRoute =
  DashboardConnectionStatusRouteImport.update({
    id: '/connection-status',
    path: '/connection-status',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardConnectionSettingsRoute =
  DashboardConnectionSettingsRouteImport.update({
    id: '/connection-settings',
    path: '/connection-settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pdf-view': typeof PdfViewRoute
  '/dashboard/connection-settings': typeof DashboardConnectionSettingsRoute
  '/dashboard/connection-status': typeof DashboardConnectionStatusRoute
  '/dashboard/pdf-picker': typeof DashboardPdfPickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pdf-view': typeof PdfViewRoute
  '/dashboard/connection-settings': typeof DashboardConnectionSettingsRoute
  '/dashboard/connection-status': typeof DashboardConnectionStatusRoute
  '/dashboard/pdf-picker': typeof DashboardPdfPickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pdf-view': typeof PdfViewRoute
  '/dashboard/connection-settings': typeof DashboardConnectionSettingsRoute
  '/dashboard/connection-status': typeof DashboardConnectionStatusRoute
  '/dashboard/pdf-picker': typeof DashboardPdfPickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pdf-view'
    | '/dashboard/connection-settings'
    | '/dashboard/connection-status'
    | '/dashboard/pdf-picker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pdf-view'
    | '/dashboard/connection-settings'
    | '/dashboard/connection-status'
    | '/dashboard/pdf-picker'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pdf-view'
    | '/dashboard/connection-settings'
    | '/dashboard/connection-status'
    | '/dashboard/pdf-picker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PdfViewRoute: typeof PdfViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf-view': {
      id: '/pdf-view'
      path: '/pdf-view'
      fullPath: '/pdf-view'
      preLoaderRoute: typeof PdfViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pdf-picker': {
      id: '/dashboard/pdf-picker'
      path: '/pdf-picker'
      fullPath: '/dashboard/pdf-picker'
      preLoaderRoute: typeof DashboardPdfPickerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/connection-status': {
      id: '/dashboard/connection-status'
      path: '/connection-status'
      fullPath: '/dashboard/connection-status'
      preLoaderRoute: typeof DashboardConnectionStatusRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/connection-settings': {
      id: '/dashboard/connection-settings'
      path: '/connection-settings'
      fullPath: '/dashboard/connection-settings'
      preLoaderRoute: typeof DashboardConnectionSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConnectionSettingsRoute: typeof DashboardConnectionSettingsRoute
  DashboardConnectionStatusRoute: typeof DashboardConnectionStatusRoute
  DashboardPdfPickerRoute: typeof DashboardPdfPickerRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConnectionSettingsRoute: DashboardConnectionSettingsRoute,
  DashboardConnectionStatusRoute: DashboardConnectionStatusRoute,
  DashboardPdfPickerRoute: DashboardPdfPickerRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PdfViewRoute: PdfViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
