/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Transformation_pipelineRouteRouteImport } from './routes/transformation_pipeline/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Transformation_pipelineIndexRouteImport } from './routes/transformation_pipeline/index'
import { Route as Transformation_pipelineModulesRouteImport } from './routes/transformation_pipeline/modules'
import { Route as Transformation_pipelineGraphNewRouteImport } from './routes/transformation_pipeline/graphNew'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardEtoInfoRouteImport } from './routes/dashboard/eto-info'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardSettingsEmailConfigsRouteImport } from './routes/dashboard/settings/email-configs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Transformation_pipelineRouteRoute =
  Transformation_pipelineRouteRouteImport.update({
    id: '/transformation_pipeline',
    path: '/transformation_pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Transformation_pipelineIndexRoute =
  Transformation_pipelineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Transformation_pipelineRouteRoute,
  } as any)
const Transformation_pipelineModulesRoute =
  Transformation_pipelineModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => Transformation_pipelineRouteRoute,
  } as any)
const Transformation_pipelineGraphNewRoute =
  Transformation_pipelineGraphNewRouteImport.update({
    id: '/graphNew',
    path: '/graphNew',
    getParentRoute: () => Transformation_pipelineRouteRoute,
  } as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEtoInfoRoute = DashboardEtoInfoRouteImport.update({
  id: '/eto-info',
  path: '/eto-info',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsEmailConfigsRoute =
  DashboardSettingsEmailConfigsRouteImport.update({
    id: '/email-configs',
    path: '/email-configs',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/transformation_pipeline': typeof Transformation_pipelineRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/eto-info': typeof DashboardEtoInfoRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/transformation_pipeline/graphNew': typeof Transformation_pipelineGraphNewRoute
  '/transformation_pipeline/modules': typeof Transformation_pipelineModulesRoute
  '/transformation_pipeline/': typeof Transformation_pipelineIndexRoute
  '/dashboard/settings/email-configs': typeof DashboardSettingsEmailConfigsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/eto-info': typeof DashboardEtoInfoRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/transformation_pipeline/graphNew': typeof Transformation_pipelineGraphNewRoute
  '/transformation_pipeline/modules': typeof Transformation_pipelineModulesRoute
  '/transformation_pipeline': typeof Transformation_pipelineIndexRoute
  '/dashboard/settings/email-configs': typeof DashboardSettingsEmailConfigsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/transformation_pipeline': typeof Transformation_pipelineRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/eto-info': typeof DashboardEtoInfoRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/transformation_pipeline/graphNew': typeof Transformation_pipelineGraphNewRoute
  '/transformation_pipeline/modules': typeof Transformation_pipelineModulesRoute
  '/transformation_pipeline/': typeof Transformation_pipelineIndexRoute
  '/dashboard/settings/email-configs': typeof DashboardSettingsEmailConfigsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/transformation_pipeline'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/eto-info'
    | '/dashboard/home'
    | '/dashboard/templates'
    | '/transformation_pipeline/graphNew'
    | '/transformation_pipeline/modules'
    | '/transformation_pipeline/'
    | '/dashboard/settings/email-configs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/eto-info'
    | '/dashboard/home'
    | '/dashboard/templates'
    | '/transformation_pipeline/graphNew'
    | '/transformation_pipeline/modules'
    | '/transformation_pipeline'
    | '/dashboard/settings/email-configs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/transformation_pipeline'
    | '/login'
    | '/dashboard/settings'
    | '/dashboard/eto-info'
    | '/dashboard/home'
    | '/dashboard/templates'
    | '/transformation_pipeline/graphNew'
    | '/transformation_pipeline/modules'
    | '/transformation_pipeline/'
    | '/dashboard/settings/email-configs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  Transformation_pipelineRouteRoute: typeof Transformation_pipelineRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation_pipeline': {
      id: '/transformation_pipeline'
      path: '/transformation_pipeline'
      fullPath: '/transformation_pipeline'
      preLoaderRoute: typeof Transformation_pipelineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation_pipeline/': {
      id: '/transformation_pipeline/'
      path: '/'
      fullPath: '/transformation_pipeline/'
      preLoaderRoute: typeof Transformation_pipelineIndexRouteImport
      parentRoute: typeof Transformation_pipelineRouteRoute
    }
    '/transformation_pipeline/modules': {
      id: '/transformation_pipeline/modules'
      path: '/modules'
      fullPath: '/transformation_pipeline/modules'
      preLoaderRoute: typeof Transformation_pipelineModulesRouteImport
      parentRoute: typeof Transformation_pipelineRouteRoute
    }
    '/transformation_pipeline/graphNew': {
      id: '/transformation_pipeline/graphNew'
      path: '/graphNew'
      fullPath: '/transformation_pipeline/graphNew'
      preLoaderRoute: typeof Transformation_pipelineGraphNewRouteImport
      parentRoute: typeof Transformation_pipelineRouteRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/eto-info': {
      id: '/dashboard/eto-info'
      path: '/eto-info'
      fullPath: '/dashboard/eto-info'
      preLoaderRoute: typeof DashboardEtoInfoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/email-configs': {
      id: '/dashboard/settings/email-configs'
      path: '/email-configs'
      fullPath: '/dashboard/settings/email-configs'
      preLoaderRoute: typeof DashboardSettingsEmailConfigsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsEmailConfigsRoute: typeof DashboardSettingsEmailConfigsRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsEmailConfigsRoute: DashboardSettingsEmailConfigsRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardEtoInfoRoute: typeof DashboardEtoInfoRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardEtoInfoRoute: DashboardEtoInfoRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface Transformation_pipelineRouteRouteChildren {
  Transformation_pipelineGraphNewRoute: typeof Transformation_pipelineGraphNewRoute
  Transformation_pipelineModulesRoute: typeof Transformation_pipelineModulesRoute
  Transformation_pipelineIndexRoute: typeof Transformation_pipelineIndexRoute
}

const Transformation_pipelineRouteRouteChildren: Transformation_pipelineRouteRouteChildren =
  {
    Transformation_pipelineGraphNewRoute: Transformation_pipelineGraphNewRoute,
    Transformation_pipelineModulesRoute: Transformation_pipelineModulesRoute,
    Transformation_pipelineIndexRoute: Transformation_pipelineIndexRoute,
  }

const Transformation_pipelineRouteRouteWithChildren =
  Transformation_pipelineRouteRoute._addFileChildren(
    Transformation_pipelineRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  Transformation_pipelineRouteRoute:
    Transformation_pipelineRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
