"""
Pipeline Executor
Executes compiled pipelines using Dask for parallel processing
"""

import time
import json
from datetime import datetime
from typing import Dict, Any, List, Literal, Optional, Tuple
from dask import delayed, compute
import logging

from shared.types.execution_result import RunResult, ExecutionError
from shared.types.execution_context import ExecutionContext
from shared.types.execution import ExecutionRunCreate, ExecutionStepCreate
from shared.typespipeline_definition_steps import PipelineStep
from shared.typespipeline_definitions import InstanceNodePin, PipelineState
from shared.utils.registry import ModuleRegistry

logger = logging.getLogger(__name__)


class PipelineExecutor:
    """Executes compiled pipelines using Dask for parallel processing"""

    def __init__(self):
        # Only module registry needed, no repositories
        self.registry = ModuleRegistry()

    def run_pipeline(
        self,
        pipeline_id: str,
        run_id: str,  # Generated by service layer
        steps: List[PipelineStep],  # Domain objects from shared.models
        entry_values: Dict[str, Any],
        pipeline_state: "PipelineState",  # Pipeline state to extract entry points from
        *,
        scheduler: Literal["threads", "processes", "distributed"] = "threads",
        max_workers: Optional[int] = None,
        fail_fast: bool = True,
    ) -> Tuple[ExecutionRunCreate, List[ExecutionStepCreate], RunResult]:
        """
        Execute a compiled pipeline with entry values.

        Args:
            pipeline_id: ID of the pipeline being executed
            run_id: Pre-generated execution run ID
            steps: List of PipelineStep domain objects
            entry_values: Entry point values
            scheduler: Dask scheduler type
            max_workers: Maximum number of workers for parallel execution
            fail_fast: Whether to stop on first error

        Returns:
            Tuple of:
            - ExecutionRunCreate: For creating/updating the run record
            - List[ExecutionStepCreate]: For creating step records
            - RunResult: The execution result for API response
        """
        started_at = datetime.utcnow()

        try:
            # 1. Validate entry values
            required_entries = self._get_required_entries(steps, pipeline_state)
            missing = set(required_entries) - set(entry_values.keys())
            if missing:
                raise ValueError(f"Missing required entry values: {missing}")

            # 2. Build Dask graph
            delayed_tasks, action_tasks = self._build_dask_graph(
                steps, entry_values, run_id
            )

            # 3. Execute only action tasks
            logger.info(f"Executing {len(action_tasks)} action tasks for run {run_id}")
            results = compute(*action_tasks, scheduler=scheduler)

            # 4. Process results into domain objects
            step_creates, actions, errors, timings = self._process_results(results)

            completed_at = datetime.utcnow()
            status = "failed" if errors else "success"

            # 5. Create domain objects for return
            run_create = ExecutionRunCreate(
                run_id=run_id,
                pipeline_id=pipeline_id,
                status=status,
                started_at=started_at,
                entry_values=entry_values,
                # completed_at will be set by service when persisting
            )

            run_result = RunResult(
                status=status,
                run_id=run_id,
                started_at=started_at.isoformat(),
                completed_at=completed_at.isoformat(),
                actions=actions,
                errors=errors,
                timings=timings,
            )

            return run_create, step_creates, run_result

        except Exception as e:
            logger.error(f"Pipeline execution failed: {e}", exc_info=True)

            # Create minimal domain objects for failed execution
            completed_at = datetime.utcnow()

            run_create = ExecutionRunCreate(
                run_id=run_id,
                pipeline_id=pipeline_id,
                status="failed",
                started_at=started_at,
                entry_values=entry_values,
                # completed_at will be set by service when persisting
            )

            run_result = RunResult(
                status="failed",
                run_id=run_id,
                started_at=started_at.isoformat(),
                completed_at=completed_at.isoformat(),
                errors=[
                    ExecutionError(
                        code="EXECUTION_FAILED", message=str(e), module_instance_id=None
                    )
                ],
                actions=[],
                timings={},
            )

            return run_create, [], run_result

    def _build_dask_graph(self, steps, entry_values, run_id):
        """Build the Dask delayed task graph"""

        # Maps for tracking tasks
        delayed_by_module = {}
        producer_of_pin = {}

        # Create entry tasks
        @delayed(pure=True)
        def _entry_passthrough(v):
            return v

        for entry_id, value in entry_values.items():
            producer_of_pin[entry_id] = _entry_passthrough(value)

        # Create task for each step
        action_tasks = []
        for step in steps:
            task = self._make_task(step, producer_of_pin, run_id)
            delayed_by_module[step.module_instance_id] = task

            # Track output producers
            if step.node_metadata:
                # Debug logging to understand the type
                logger.debug(
                    f"node_metadata type for {step.module_instance_id}: {type(step.node_metadata)}"
                )

                # Handle both dict and potential string cases
                if isinstance(step.node_metadata, str):
                    logger.warning(
                        f"node_metadata is string for {step.module_instance_id}, attempting to parse"
                    )
                    import json

                    try:
                        metadata = json.loads(step.node_metadata)
                        outputs = (
                            metadata.get("outputs", [])
                            if isinstance(metadata, dict)
                            else []
                        )
                    except json.JSONDecodeError:
                        logger.error(
                            f"Failed to parse node_metadata JSON for {step.module_instance_id}"
                        )
                        outputs = []
                elif isinstance(step.node_metadata, dict):
                    outputs = step.node_metadata.get("outputs", [])
                else:
                    logger.warning(
                        f"Unexpected node_metadata type: {type(step.node_metadata)}"
                    )
                    outputs = []

                for output in outputs:
                    # outputs is List[InstanceNodePin] or list of dicts
                    # Access node_id whether it's an object or dict
                    if hasattr(output, "node_id"):
                        node_id = output.node_id
                    elif isinstance(output, dict):
                        node_id = output.get("node_id")
                    else:
                        logger.warning(f"Unexpected output type: {type(output)}")
                        continue

                    if node_id:
                        producer_of_pin[node_id] = task

            # Track action tasks
            if step.module_kind == "action":
                action_tasks.append(task)

        return delayed_by_module, action_tasks

    def _make_task(self, step, producer_of_pin, run_id):
        """Create a delayed task for a pipeline step"""

        # Resolve module handler
        # module_ref is in format "module_id:version", we need just the module_id
        module_id = (
            step.module_ref.split(":")[0] if ":" in step.module_ref else step.module_ref
        )
        handler_cls = self.registry.get(module_id)

        if not handler_cls:
            # If not in registry, try to load from handler if available
            handler_cls = self.registry.resolve_module(module_id)

        if not handler_cls:
            raise ValueError(
                f"Module not found: {module_id} (from ref: {step.module_ref})"
            )

        handler = handler_cls()

        # Prepare dependencies
        deps = {}
        for input_pin, source_pin in step.input_field_mappings.items():
            # input_field_mappings is Dict[str, str] mapping input_pin_id -> source_node_id
            if source_pin in producer_of_pin:
                deps[source_pin] = producer_of_pin[source_pin]
            else:
                raise ValueError(f"No producer for pin {source_pin}")

        @delayed(pure=(step.module_kind != "action"))
        def _run_instance(
            module_class=handler_cls, module_handler=handler, **upstream_outputs
        ):
            t0 = time.perf_counter()
            executed_at = datetime.utcnow()

            # Build inputs
            # Extract the actual values from upstream outputs
            # upstream_outputs[source_pin] contains the full result dict with "outputs" key
            # We need to extract the specific value from the outputs dict
            inputs = {}
            for input_pin, source_pin in step.input_field_mappings.items():
                upstream_result = upstream_outputs[source_pin]
                # If upstream result has the full structure, extract from outputs
                if isinstance(upstream_result, dict) and "outputs" in upstream_result:
                    # The outputs is a dict with node_id as key, extract the value for source_pin
                    outputs_dict = upstream_result["outputs"]
                    # The source_pin is the node_id we're looking for
                    inputs[input_pin] = outputs_dict.get(source_pin, outputs_dict)
                else:
                    # Direct value (for entry points or legacy format)
                    inputs[input_pin] = upstream_result

            # Create execution context
            # Extract inputs and outputs from node_metadata dict
            if isinstance(step.node_metadata, str):
                # Parse JSON string if needed
                try:
                    metadata = json.loads(step.node_metadata)
                except json.JSONDecodeError:
                    logger.error(
                        f"Failed to parse node_metadata for {step.module_instance_id}"
                    )
                    metadata = {}
            elif isinstance(step.node_metadata, dict):
                metadata = step.node_metadata
            else:
                metadata = {}

            # Convert InstanceNodePin objects to dicts if needed for ExecutionContext
            input_pins = metadata.get("inputs", []) if metadata else []
            output_pins = metadata.get("outputs", []) if metadata else []

            # Ensure pins are in dict format for Pydantic validation
            if input_pins and hasattr(input_pins[0], "model_dump"):
                input_pins = [pin.model_dump() for pin in input_pins]
            elif input_pins and hasattr(input_pins[0], "dict"):
                input_pins = [pin.dict() for pin in input_pins]

            if output_pins and hasattr(output_pins[0], "model_dump"):
                output_pins = [pin.model_dump() for pin in output_pins]
            elif output_pins and hasattr(output_pins[0], "dict"):
                output_pins = [pin.dict() for pin in output_pins]

            context = ExecutionContext(
                inputs=input_pins,
                outputs=output_pins,
                module_instance_id=step.module_instance_id,
                run_id=run_id,
            )

            try:
                # Convert config dict to the module's ConfigModel instance
                config_instance = module_class.ConfigModel(**step.module_config)
                outputs = module_handler.run(inputs, config_instance, context)
                ok = True
                err = None
            except Exception as e:
                ok = False
                outputs = {}
                err = f"{e.__class__.__name__}: {e}"
                logger.error(
                    f"Module {step.module_instance_id} failed: {err}", exc_info=True
                )

            t1 = time.perf_counter()
            elapsed_ms = (t1 - t0) * 1000.0

            # Return all data needed for tracking
            return {
                "__ok__": ok,
                "__err__": err,
                "__elapsed_ms__": elapsed_ms,
                "__module_instance_id__": step.module_instance_id,
                "__module_kind__": step.module_kind,
                "__step_number__": step.step_number,
                "__inputs__": inputs,  # Keep for tracking
                "__executed_at__": executed_at,
                "__run_id__": run_id,  # Pass through for ExecutionStepCreate
                "outputs": outputs,
            }

        return _run_instance(**deps)

    def _get_required_entries(self, steps, pipeline_state):
        """Extract required entry pins from steps"""
        # Get entry point IDs from the pipeline state
        entry_point_ids = {ep.node_id for ep in pipeline_state.entry_points}

        # Find which entry points are actually used by the steps
        required = set()
        for step in steps:
            # input_field_mappings is Dict[str, str] mapping input_pin_id -> source_node_id
            for input_pin_id, source_node_id in step.input_field_mappings.items():
                if source_node_id in entry_point_ids:
                    required.add(source_node_id)

        return required

    def _process_results(
        self, results
    ) -> Tuple[
        List[ExecutionStepCreate], List[Dict], List[ExecutionError], Dict[str, float]
    ]:
        """
        Process execution results into domain objects.

        Returns:
            Tuple of:
            - List[ExecutionStepCreate]: Step execution records
            - List[Dict]: Action outputs
            - List[ExecutionError]: Execution errors
            - Dict[str, float]: Timing information
        """
        step_creates = []
        actions = []
        errors = []
        timings = {}

        for env in results:
            mid = env["__module_instance_id__"]
            timings[mid] = env["__elapsed_ms__"]

            # Create ExecutionStepCreate domain object
            step_create = ExecutionStepCreate(
                run_id=env["__run_id__"],
                module_instance_id=mid,
                step_number=env["__step_number__"],
                inputs=env["__inputs__"],
                outputs=env["outputs"],
                elapsed_ms=env["__elapsed_ms__"],
                error=env["__err__"],
                executed_at=env["__executed_at__"],
            )
            step_creates.append(step_create)

            if not env["__ok__"]:
                errors.append(
                    ExecutionError(
                        code="MODULE_FAILED",
                        message=env["__err__"],
                        module_instance_id=mid,
                    )
                )
            else:
                actions.append({"module_instance_id": mid, "outputs": env["outputs"]})

        return step_creates, actions, errors, timings
