"""add processing status fields to pending_action_fields

Revision ID: 054f36f4593a
Revises: 83cd3c12da09
Create Date: 2026-01-23 18:23:37.917786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054f36f4593a'
down_revision: Union[str, Sequence[str], None] = '83cd3c12da09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_action_fields', sa.Column('processing_status', sa.String(length=20), server_default='success', nullable=False))
    op.add_column('pending_action_fields', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('pending_action_fields', sa.Column('raw_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # MSSQL requires dropping default constraints before dropping columns
    op.execute("""
        DECLARE @constraint_name NVARCHAR(255)
        SELECT @constraint_name = name FROM sys.default_constraints
        WHERE parent_object_id = OBJECT_ID('pending_action_fields')
        AND col_name(parent_object_id, parent_column_id) = 'processing_status'
        IF @constraint_name IS NOT NULL
            EXEC('ALTER TABLE pending_action_fields DROP CONSTRAINT ' + @constraint_name)
    """)
    op.drop_column('pending_action_fields', 'raw_value')
    op.drop_column('pending_action_fields', 'processing_error')
    op.drop_column('pending_action_fields', 'processing_status')
