/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as LoginRouteImport } from './pages/login'
import { Route as DashboardRouteRouteImport } from './pages/dashboard/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as DashboardPipelinesIndexRouteImport } from './pages/dashboard/pipelines/index'
import { Route as DashboardPdfTemplatesIndexRouteImport } from './pages/dashboard/pdf-templates/index'
import { Route as DashboardEtoIndexRouteImport } from './pages/dashboard/eto/index'
import { Route as DashboardConfigsIndexRouteImport } from './pages/dashboard/configs/index'
import { Route as DashboardPipelinesCreateRouteImport } from './pages/dashboard/pipelines/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPipelinesIndexRoute = DashboardPipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPdfTemplatesIndexRoute =
  DashboardPdfTemplatesIndexRouteImport.update({
    id: '/pdf-templates/',
    path: '/pdf-templates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEtoIndexRoute = DashboardEtoIndexRouteImport.update({
  id: '/eto/',
  path: '/eto/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfigsIndexRoute = DashboardConfigsIndexRouteImport.update({
  id: '/configs/',
  path: '/configs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPipelinesCreateRoute =
  DashboardPipelinesCreateRouteImport.update({
    id: '/pipelines/create',
    path: '/pipelines/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pipelines/create': typeof DashboardPipelinesCreateRoute
  '/dashboard/configs': typeof DashboardConfigsIndexRoute
  '/dashboard/eto': typeof DashboardEtoIndexRoute
  '/dashboard/pdf-templates': typeof DashboardPdfTemplatesIndexRoute
  '/dashboard/pipelines': typeof DashboardPipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pipelines/create': typeof DashboardPipelinesCreateRoute
  '/dashboard/configs': typeof DashboardConfigsIndexRoute
  '/dashboard/eto': typeof DashboardEtoIndexRoute
  '/dashboard/pdf-templates': typeof DashboardPdfTemplatesIndexRoute
  '/dashboard/pipelines': typeof DashboardPipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pipelines/create': typeof DashboardPipelinesCreateRoute
  '/dashboard/configs/': typeof DashboardConfigsIndexRoute
  '/dashboard/eto/': typeof DashboardEtoIndexRoute
  '/dashboard/pdf-templates/': typeof DashboardPdfTemplatesIndexRoute
  '/dashboard/pipelines/': typeof DashboardPipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/pipelines/create'
    | '/dashboard/configs'
    | '/dashboard/eto'
    | '/dashboard/pdf-templates'
    | '/dashboard/pipelines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/pipelines/create'
    | '/dashboard/configs'
    | '/dashboard/eto'
    | '/dashboard/pdf-templates'
    | '/dashboard/pipelines'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/pipelines/create'
    | '/dashboard/configs/'
    | '/dashboard/eto/'
    | '/dashboard/pdf-templates/'
    | '/dashboard/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pipelines/': {
      id: '/dashboard/pipelines/'
      path: '/pipelines'
      fullPath: '/dashboard/pipelines'
      preLoaderRoute: typeof DashboardPipelinesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pdf-templates/': {
      id: '/dashboard/pdf-templates/'
      path: '/pdf-templates'
      fullPath: '/dashboard/pdf-templates'
      preLoaderRoute: typeof DashboardPdfTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/eto/': {
      id: '/dashboard/eto/'
      path: '/eto'
      fullPath: '/dashboard/eto'
      preLoaderRoute: typeof DashboardEtoIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/configs/': {
      id: '/dashboard/configs/'
      path: '/configs'
      fullPath: '/dashboard/configs'
      preLoaderRoute: typeof DashboardConfigsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pipelines/create': {
      id: '/dashboard/pipelines/create'
      path: '/pipelines/create'
      fullPath: '/dashboard/pipelines/create'
      preLoaderRoute: typeof DashboardPipelinesCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPipelinesCreateRoute: typeof DashboardPipelinesCreateRoute
  DashboardConfigsIndexRoute: typeof DashboardConfigsIndexRoute
  DashboardEtoIndexRoute: typeof DashboardEtoIndexRoute
  DashboardPdfTemplatesIndexRoute: typeof DashboardPdfTemplatesIndexRoute
  DashboardPipelinesIndexRoute: typeof DashboardPipelinesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPipelinesCreateRoute: DashboardPipelinesCreateRoute,
  DashboardConfigsIndexRoute: DashboardConfigsIndexRoute,
  DashboardEtoIndexRoute: DashboardEtoIndexRoute,
  DashboardPdfTemplatesIndexRoute: DashboardPdfTemplatesIndexRoute,
  DashboardPipelinesIndexRoute: DashboardPipelinesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
