/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PdfFilesRouteImport } from './pages/pdf-files'
import { Route as IndexRouteImport } from './pages/index'
import { Route as TemplatesIndexRouteImport } from './pages/templates/index'
import { Route as PipelinesIndexRouteImport } from './pages/pipelines/index'
import { Route as EtoRunsIndexRouteImport } from './pages/eto-runs/index'
import { Route as EmailConfigsIndexRouteImport } from './pages/email-configs/index'

const PdfFilesRoute = PdfFilesRouteImport.update({
  id: '/pdf-files',
  path: '/pdf-files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtoRunsIndexRoute = EtoRunsIndexRouteImport.update({
  id: '/eto-runs/',
  path: '/eto-runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfigsIndexRoute = EmailConfigsIndexRouteImport.update({
  id: '/email-configs/',
  path: '/email-configs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pdf-files': typeof PdfFilesRoute
  '/email-configs': typeof EmailConfigsIndexRoute
  '/eto-runs': typeof EtoRunsIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pdf-files': typeof PdfFilesRoute
  '/email-configs': typeof EmailConfigsIndexRoute
  '/eto-runs': typeof EtoRunsIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pdf-files': typeof PdfFilesRoute
  '/email-configs/': typeof EmailConfigsIndexRoute
  '/eto-runs/': typeof EtoRunsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pdf-files'
    | '/email-configs'
    | '/eto-runs'
    | '/pipelines'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pdf-files'
    | '/email-configs'
    | '/eto-runs'
    | '/pipelines'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/pdf-files'
    | '/email-configs/'
    | '/eto-runs/'
    | '/pipelines/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PdfFilesRoute: typeof PdfFilesRoute
  EmailConfigsIndexRoute: typeof EmailConfigsIndexRoute
  EtoRunsIndexRoute: typeof EtoRunsIndexRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf-files': {
      id: '/pdf-files'
      path: '/pdf-files'
      fullPath: '/pdf-files'
      preLoaderRoute: typeof PdfFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eto-runs/': {
      id: '/eto-runs/'
      path: '/eto-runs'
      fullPath: '/eto-runs'
      preLoaderRoute: typeof EtoRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-configs/': {
      id: '/email-configs/'
      path: '/email-configs'
      fullPath: '/email-configs'
      preLoaderRoute: typeof EmailConfigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PdfFilesRoute: PdfFilesRoute,
  EmailConfigsIndexRoute: EmailConfigsIndexRoute,
  EtoRunsIndexRoute: EtoRunsIndexRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
